In [1]:
#import the libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC

In [2]:
#import dataset
data  = pd.read_csv("/content/Iris.csv")

In [3]:
#print the data
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [4]:
print(data)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  

In [5]:
#calculate the shape of the data
data.shape

(150, 6)

In [6]:
#use Label
encode = LabelEncoder()

data.Species = encode.fit_transform(data.Species)

In [7]:
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

In [8]:
#create features
X = data[["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]]

In [9]:
X

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [10]:
#define target/dependent variable
Y = data["Species"]

In [11]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64

In [12]:
#convert features into numpy array
X = np.array(X)

In [13]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [14]:
#convert target variable into numpy array
Y = np.array(Y)

In [15]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [17]:
#train test split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size =0.2)

In [18]:
X_train

array([[6.1, 2.6, 5.6, 1.4],
       [5.7, 2.5, 5. , 2. ],
       [7.7, 3.8, 6.7, 2.2],
       [5.5, 2.4, 3.7, 1. ],
       [4.4, 3.2, 1.3, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [5.7, 2.6, 3.5, 1. ],
       [4.4, 2.9, 1.4, 0.2],
       [5.5, 2.3, 4. , 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5. , 3.4, 1.6, 0.4],
       [5.1, 2.5, 3. , 1.1],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [6.9, 3.2, 5.7, 2.3],
       [4.8, 3.4, 1.6, 0.2],
       [6.8, 3. , 5.5, 2.1],
       [4.9, 3.1, 1.5, 0.1],
       [6.3, 2.3, 4.4, 1.3],
       [5.8, 2.6, 4. , 1.2],
       [6.3, 2.5, 5. , 1.9],
       [6.1, 2.9, 4.7, 1.4],
       [4.9, 2.5, 4.5, 1.7],
       [4.8, 3.4, 1.9, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [7.2, 3.6, 6.1, 2.5],
       [5.1, 3.5, 1.4, 0.3],
       [5. , 3.5, 1.6, 0.6],
       [7.7, 2.8, 6.7, 2. ],
       [5.4, 3.4, 1.7, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [7.2, 3.2, 6. , 1.8],
       [5.6, 2

In [19]:
X_train.shape

(120, 4)

In [20]:
Y_test.shape

(30,)

In [22]:
X_test.shape

(30, 4)

In [21]:
#create instance of our model
model = SVC()

model.fit(X_train,Y_train)

SVC()

In [25]:
Y_test

array([0, 2, 1, 0, 0, 1, 1, 2, 0, 2, 0, 2, 1, 2, 1, 0, 1, 0, 1, 0, 2, 1,
       0, 2, 1, 0, 2, 2, 2, 2])

In [23]:
#predict the outcome
pred = model.predict(X_test)

In [24]:
pred

array([0, 2, 1, 0, 0, 1, 1, 2, 0, 2, 0, 2, 1, 2, 1, 0, 1, 0, 1, 0, 2, 1,
       0, 2, 1, 0, 2, 2, 2, 2])

In [26]:
#calculate the accuracy of model
model.score(X_test,Y_test)

1.0